config/routes.rb
Rails.application.routes.draw do
  get 'posts/main'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/" => "root#top"
get "/main" => "posts#main"

get "/posts" => "posts#main"
post "/posts" => "posts#create"

get "/posts/:id" => "posts#show", as: "post"

get "/posts/:id/edit" => "posts#edit", as: "edit_post"

patch "/posts/:id" => "posts#update", as: "update_post"

delete "/posts/main/:id" => "posts#destroy", as: "destroy_post"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def main
  	@posts = Post.all

  	@post = Post.new
  	flash[:success] = "successfully"
  end
  def create
  	  post = Post.new(post_params)
  	  post.save
  	  redirect_to post_path(post.id)
  end
  def show
  	@post = Post.find(params[:id])
  end
  def edit
  	@post = Post.find(params[:id])
  end
  def update
  		post = Post.find(params[:id])
  		post.update(post_params)
  		redirect_to post_path(post.id)
  		flash[:success] = "successfully"
  end
  def destroy
  		post = Post.find(params[:id])
  		post.destroy
  		redirect_to posts_path
  end


  private
  def post_params
  	  params.require(:post).permit(:title, :body)
  end

end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@post) do |f| %>
	<h4>Title</h4>
	 <div class="box">
		<%= f.text_field :title, class: "book_title" %>
	 </div>
	<h4>Body</h4>
	 <div class="box">
	 	<%= f.text_area :body, class: "book_body" %>
	 </div>
	 <div class="box">
	 	<%= f.submit "Update Book " %>
	 </div>
	 <%= link_to "Show", post_path(@post.id), class: "show_#{@post.id}" %>
	 <%= link_to "Back", posts_path, class: "back" %>

<% end %>

app/views/posts/main.html.erb
<h1>Books</h1>


<table>
  <thead>
	<tr>
		<th>Title</th>
		<th>Body</th>
		<th>   </th>
	</tr>

  </thead>
<% @posts.each do |post| %>
  <tbody>
	<tr>
		<td><%= post.title %></td>
		<td><%= post.body %></td>
		<td>
			<%=link_to "Show", post_path(post.id), class: "show_#{post.id}" %>
	    </td>
	    <td>
	    	<%= link_to "Edit", edit_post_path(post.id), class: "edit_#{post.id}" %>
	    </td>
	    <td><%= link_to "Destroy", destroy_post_path(post.id), method: :delete, "date-confirm" => "Are you sure?", class: "destroy_#{post.id}" %>
	    </td>
	</tr>
  </tbody>
  <% end %>
</table>



<%= form_for(@post) do |f| %>

<h2>New book</h2>
 <h4>title</h4>
 <div class="box">
 	<%= f.text_field :title, class: "book_title" %>
 </div>

 <h4>body</h4>
 <div class="box">
	<%= f.text_area :body, class: "book_body" %>
 </div>

 <div class="box">
	<%= f.submit "Create Book" %>
 </div>

<% end %>

app/views/posts/show.html.erb
<%= flash[:success] %>
<p class="s-title">Title:</p>
	<div class="show"><%= @post.title %></div>
<p class="s-title">Body</p>
	<div class="show"><%= @post.body %></div>

<%= link_to "Edit", edit_post_path(@post.id),class: "edit_#{@post.id}" %>
<%=link_to "Back", posts_path, class: "back" %>

app/views/root/top.html.erb
<h1>ようこそ Bookers へ！</h1>
	<p class="title-ex">Bookersでは、さまざまな書籍に関するあなたの意見や
	</p>
	<p class="title-ex-2">印象を共有し交換することができます</p>
	<a href ="/main">start</a>